### ISSUE TITLE
Implement automated coins file updates

### ISSUE THREAD

**Issue by smk762** [KomodoPlatform/mm2-client#4]
Looks the 0.5.6 coins file was still in use, tho we released 0.5.6a a little while ago. 
Similar to https://github.com/KomodoPlatform/atomicDEX-Desktop/issues/2035 we could use an API to define and pin latest coins file, then via cron on server, update if required.

**Comment by SirSevenG** [comment]
@smk762 Was one a while ago, we can close this one. )
